database:
  type: sqlite
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: root
  table: my_database
  #每10分钟同步一次
  user-container-sync-time: 360000
options:
  debug: false
  read:
    #当行中有这些之一时，忽略此行属性
    ignores:
      - "//"
      - "§-"
  condition:
    line-condition:
      #单行条件的格式
      #解析:
      # \/ '\'用来转义，   :  属性和单行条件之间的分隔符
      # (?<requirement>.*) : 单行条件们
      # 例： 攻击力: 100/Lv.100,职业: 巫师
      format: '\/(?<requirement>.*)'
      #每个单行条件间的分隔符
      separator: ","
  operation:
    string-append-separator: ", "

