options:
  debug: false
  #生命值缩放
  fight:
    #原版弓弩伤害是否会按攻击者射箭时的属性计算 而非射中时的属性
    arrow-cache-data: true
    #是否进行非玩家实体间的战斗计算
    eve-fight-cal: false
    vanilla-armor: true
    attack-fight: { }
    #若没有这些权限，则攻击时运行默认的 attack 战斗组
    #当攻击者拥有这个权限时，攻击时将运行 class-a-attack 战斗组
    #      as.class.a: class-a-attack
    # as.class.b: class-b-attack
  read:
    #当行中有这些之一时，忽略此行属性
    ignores:
      - "//"
      - "§-"
    #数字格式，这个最好不要乱动
    # ?<value>不要改，后面的正则可以改
    number-pattern: '(?<value>(\+|\-)?(\d+(?:(\.\d+))?))'
  condition:
    line-condition:
      #单行条件的格式
      #解析:
      # .* 匹配任意多个字符 : 用于匹配属性名及其值
      # \/ '\'用来转义，   :  属性和单行条件之间的分隔符
      # (?<requirement>.*) : 单行条件们
      # 例： 攻击力: 100/Lv.100,职业: 巫师
      format: '\/(?<requirement>.*)'
      #每个单行条件间的分隔符
      separator: ","
  operation:
    string-append-separator: ", "

