name: build-api
on:
  push:
    branches:
      - main
jobs:
  build-api:
    name: Build API Jar
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8.0
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        continue-on-error: true
        id: build_api_1
        run: ./gradlew build -Papi=true -Porder=$GITHUB_RUN_NUMBER
      - name: build (retry 1)
        continue-on-error: true
        id: build_api_2
        if: steps.build_api_1.outcome == 'failure'
        run: ./gradlew build -Papi=true -Porder=$GITHUB_RUN_NUMBER
      - name: build (retry 2)
        continue-on-error: true
        id: build_api_3
        if: steps.build_api_2.outcome == 'failure'
        run: ./gradlew build -Papi=true -Porder=$GITHUB_RUN_NUMBER
      - name: build (retry 3)
        id: build_api_4
        if: steps.build_api_3.outcome == 'failure'
        run: ./gradlew build -Papi=true -Porder=$GITHUB_RUN_NUMBER
      # 上传构建文件
      - name: capture build api artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs