#on-attack:
#  triggers: [ custom entity fight ]
#  namespaces: [ bukkit ]
#  when:
#    - if: "check &attacker name; == 'Neige'"
#      goto: main1
#    - else: main
#  context:
#    attackerData: attr data of &attacker
#    defenderData: attr data of &defender
#  functions:
#    main: |-
#      set addition_damage to math &attackerData.攻击力.value - &defenderData.防御力.value
#      damage &defender &addition_damage
#      particle REDSTONE at @defender eyeLocation; {
#        'range' = 100
#        count = 1000
#        data = particleData dust [ color [ 255 255 235 ] in 1.0 ]
#      }
#    main1: |-
#      tell all 'Neige 打人了!'
