name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8.0
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      # 第一次构建
      - name: build
        continue-on-error: true
        id: build_1
        run: ./gradlew build -Porder=$GITHUB_RUN_NUMBER
      # 第二次构建
      - name: build (retry 1)
        continue-on-error: true
        id: build_2
        if: steps.build_1.outcome == 'failure'
        run: ./gradlew build -Porder=$GITHUB_RUN_NUMBER
      # 第三次构建
      - name: build (retry 2)
        continue-on-error: true
        id: build_3
        if: steps.build_2.outcome == 'failure'
        run: ./gradlew build -Porder=$GITHUB_RUN_NUMBER
      # 第四次构建
      - name: build (retry 3)
        id: build_4
        if: steps.build_3.outcome == 'failure'
        run: ./gradlew build -Porder=$GITHUB_RUN_NUMBER
      # 上传构建文件
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      - name: Sync version
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: main
          folder: .
          commit-message: "sync version"
  build-api:
    name: Build API Jar
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8.0
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        continue-on-error: true
        id: build_api_1
        run: ./gradlew build -Papi=true -Porder=$GITHUB_RUN_NUMBER
      - name: build (retry 1)
        continue-on-error: true
        id: build_api_2
        if: steps.build_api_1.outcome == 'failure'
        run: ./gradlew build -Papi=true -Porder=$GITHUB_RUN_NUMBER
      - name: build (retry 2)
        continue-on-error: true
        id: build_api_3
        if: steps.build_api_2.outcome == 'failure'
        run: ./gradlew build -Papi=true -Porder=$GITHUB_RUN_NUMBER
      - name: build (retry 3)
        id: build_api_4
        if: steps.build_api_3.outcome == 'failure'
        run: ./gradlew build -Papi=true -Porder=$GITHUB_RUN_NUMBER
      # 上传构建文件
      - name: capture build api artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs
  release:
    name: Release Jar
    needs: [ build, build-api ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8.0
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Download Content
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: Archive content
        uses: thedoctor0/zip-release@master
        with:
          filename: Artifacts.zip
      - name: Retrieve Release Name
        id: return_name
        run: |
          echo "::set-output name=RELEASE_NAME::$(./gradlew -q releaseName"
      - name: Get Release Name
        run: |
          echo "release_name=${{steps.return_name.outputs.RELEASE_NAME}}" >> $GITHUB_ENV
      - name: Retrieve Version
        id: return_version
        run: |
          echo "::set-output name=VERSION_NAME::$(./gradlew -q version"
      - name: Get version
        run: |
          echo "version_name=${{steps.return_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
      - name: Create release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version_name }}
          release_name: Release ${{ env.version_name }}
      - name: Upload asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./Artifacts.zip
          asset_name: ${{ env.release_name }}.zip
          asset_content_type: application/zip
